spring.application.name=shop-rating
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/shopdb
spring.datasource.username=shopuser
spring.datasource.password=shoppass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.org.springframework=INFO
logging.level.com.shopcloud.rating=DEBUG
