spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: shop-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9999

#Zipkin config
management:
  tracing:
    sampling:
      probability: 1.0
  #Actuator config
  endpoints:
    web:
      exposure:
        include: "*"
